- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      Include_vars: vars_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout